[package]
name = "nh-test-compare"
version.workspace = true
edition.workspace = true
license.workspace = true

[dependencies]
nh-core = { workspace = true }
nh-data = { workspace = true }
libc = "0.2"

[build-dependencies]
cc = "1.0"

[dev-dependencies]
serial_test = "3.0"
