[package]
name = "nh-assets"
version = "0.1.0"
edition = "2024"

[dependencies]
nh-core = { path = "../nh-core" }
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
thiserror = "2.0"
strum = { version = "0.26", features = ["derive"] }
